name: Custom Actions

on:
  workflow_dispatch:

jobs:
  test_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Persons name
        uses: ./actions
        id: characters
        with:
          person_id: ${{ github.run_number }}
      - name: Regresa el personaje
        run: echo "${{ steps.characters.outputs.person_name }}"