name: secrets

on:
  workflow_dispatch:
    
env:
    SOLUTION_PATH: ./...
    DOCKERFILE_PATH: .
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v $SOLUTION_PATH

    - name: Test
      run: go test -v $SOLUTION_PATH

  docker:
    name: Docker and build GO
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v4
    - name: docker build
      run: docker build $DOCKERFILE_PATH -t jandronit/firststeps-go:${{ github.run_number }}

    - uses: docker/login-action@v3
      name: Docker login
      with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      run: docker push jandronit/firststeps-go:${{ github.run_number }}      